//
//  DetailPokedexInterfaces.swift
//  MyPokedex
//
//  Created by Christian Adiputra on 06/03/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit

protocol DetailPokedexWireframeInterface: WireframeInterface {
}

protocol DetailPokedexViewInterface: ViewInterface {
    func updateView()
    func catchSucceeded()
    func catchFailed()
}

protocol DetailPokedexPresenterInterface: PresenterInterface {
    var pokemon: PokemonDetail? {
        get
    }
    func getDetailPokemon(id: Int)
    func getName() -> String
    func getUrl() -> String
    func getType() -> String
    func getMove() -> String
    func catchPokemon()
    func addPokemon()
}

protocol DetailPokedexInteractorInterface: InteractorInterface {
    func getDetailPokemon(id: Int)
    func getTotalPokemon() -> Int
    func addPokemon(pokemon: MyPokemon)
}

protocol DetailPokedexInteractorOutputInterface: InteractorOutputInterface {
    func didSuccessGetDetailPokemon(pokemon: PokemonDetail?)
    func didFailedGetDetailPokemon(message: String)
}
