//
//  DetailPokedexViewController.swift
//  MyPokedex
//
//  Created by Christian Adiputra on 06/03/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit

final class DetailPokedexViewController: UIViewController {
    
    var container: UIView = {
        let kit = DesignKitImp()
        let view = kit.buildRoundedView()
        view.backgroundColor = UIColor.lightGray.withAlphaComponent(0.2)
        return view
    }()
    
    var imageView: UIImageView = {
        let image = UIImageView()
        image.image = ImageProvider.image(named: "bulbasaur")
        image.layer.cornerRadius = 60
        image.contentMode = .scaleAspectFit
        image.layer.masksToBounds = true
        image.translatesAutoresizingMaskIntoConstraints = false
        return image
    }()
    
    var nameLabel: UILabel = {
        let label = UILabel()
        label.textColor = .midnightBlue
        label.font = UIFont.systemFont(ofSize: 20, weight: .bold)
        label.text = "bulbasur"
        return label
    }()
    
    var typeLabel: UILabel = {
        let label = UILabel()
        label.textColor = .midnightBlue
        label.font = UIFont.systemFont(ofSize: 16, weight: .bold)
        label.text = "Type :"
        return label
    }()
    
    var movesLabel: UILabel = {
        let label = UILabel()
        label.textColor = .midnightBlue
        label.font = UIFont.systemFont(ofSize: 16, weight: .bold)
        label.text = "Moves :"
        return label
    }()
    
    var type: UILabel = {
        let label = UILabel()
        label.textColor = .midnightBlue
        label.font = UIFont.systemFont(ofSize: 12, weight: .regular)
        return label
    }()

    var move: UILabel = {
        let label = UILabel()
        label.textColor = .midnightBlue
        label.font = UIFont.systemFont(ofSize: 12, weight: .regular)
        label.numberOfLines = 0
        return label
    }()
    
    var catchBtn: UIButton = {
        let button = UIButton()
        button.layer.cornerRadius = 8
        button.setTitle("Catch", for: .normal)
        button.backgroundColor = .greenSea
        return button
    }()
    // MARK: - Public properties -

    var presenter: DetailPokedexPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    func setupView() {
        view.backgroundColor = .white
        view.addSubview(container)
        view.addSubview(imageView)
        container.addSubview(nameLabel)
        container.addSubview(typeLabel)
        container.addSubview(type)
        container.addSubview(movesLabel)
        container.addSubview(move)
        view.addSubview(catchBtn)
        catchBtn.addTarget(self, action: #selector(catchPokemon), for: .touchUpInside)
        
        container.snp.makeConstraints { make in
            make.height.equalTo(UIScreen.main.bounds.height/3)
            make.width.equalTo(UIScreen.main.bounds.height/3)
            make.centerX.equalToSuperview()
            make.centerY.equalToSuperview()
        }
        
        imageView.snp.makeConstraints { make in
            make.width.height.equalTo(120)
            make.centerX.equalTo(container)
            make.centerY.equalTo(container.snp.top)
        }
        
        nameLabel.snp.makeConstraints { make in
            make.top.equalTo(imageView.snp.bottom).offset(-10)
            make.centerX.equalTo(container)
        }
        
        typeLabel.snp.makeConstraints { make in
            make.top.equalTo(nameLabel.snp.bottom).offset(8)
            make.left.equalTo(container.snp.left).offset(8)
        }
        
        type.snp.makeConstraints { make in
            make.top.equalTo(typeLabel.snp.bottom).offset(4)
            make.left.equalTo(container.snp.left).offset(8)
            make.right.equalTo(container.snp.right).offset(-8)
        }
        
        movesLabel.snp.makeConstraints { make in
            make.top.equalTo(type.snp.bottom).offset(10)
            make.left.equalTo(container.snp.left).offset(8)
        }
        
        move.snp.makeConstraints { make in
            make.top.equalTo(movesLabel.snp.bottom).offset(4)
            make.left.equalTo(container.snp.left).offset(8)
            make.right.equalTo(container.snp.right).offset(-8)
        }
        
        catchBtn.snp.makeConstraints { make in
            make.top.equalTo(container.snp.bottom).offset(15)
            make.width.equalTo(UIScreen.main.bounds.height/3)
            make.centerX.equalToSuperview()
            make.height.equalTo(50)
        }

    }
    
    @objc func catchPokemon() {
        presenter.catchPokemon()
    }

}

// MARK: - Extensions -

extension DetailPokedexViewController: DetailPokedexViewInterface {
    func catchSucceeded() {
        showAlert(title: "Gotcha!", message: "Success! You have obtained the Pokemon. The Pokemon has been added to your list.")
    }
    
    func catchFailed() {
        showAlert(title: "Missed!", message: "You failed to obtain the Pokemon. Please try again")
    }
    
    func updateView() {
        nameLabel.text = presenter.getName()
        imageView.kf.setImage(with: URL(string: presenter.getUrl()))
        
        self.type.text = presenter.getType()
        self.move.text = presenter.getMove()
    }
    
}

extension DetailPokedexViewController {
    func showAlert(title: String, message: String) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil
        ))
        self.present(alert, animated: true, completion: nil)
    }
}
