//
//  MyPokemonListWireframe.swift
//  MyPokedex
//
//  Created by Christian Adiputra on 15/03/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit

final class MyPokemonListWireframe: BaseWireframe<MyPokemonListViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = MyPokemonListViewController()
        super.init(viewController: moduleViewController)

        let interactor = MyPokemonListInteractor()
        let presenter = MyPokemonListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MyPokemonListWireframe: MyPokemonListWireframeInterface {
}
