//
//  MyPokemonListInterfaces.swift
//  MyPokedex
//
//  Created by Christian Adiputra on 15/03/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit
import RealmSwift

protocol MyPokemonListWireframeInterface: WireframeInterface {
}

protocol MyPokemonListViewInterface: ViewInterface {
    func updateView()
    func releaseSucceeded()
    func releaseFailed()
    func updateNameSucceess()
}

protocol MyPokemonListPresenterInterface: PresenterInterface {
    var myPokemon: [MyPokemon]? {
        get
    }
    func getListMyPokemon()
    func getPokemonName(id: ObjectId) -> String
    func updatePokemonName(id: ObjectId, name: String)
    func releasePokemon(id: ObjectId)
}

protocol MyPokemonListInteractorInterface: InteractorInterface {
    func getListMyPokemon() -> [MyPokemon]
    func updatePokemonName(id: ObjectId, name: String)
    func deletePokemon(id: ObjectId)
}

protocol MyPokemonListInteractorOutputInterface: InteractorOutputInterface {
    func successGetListMyPokemon()
}
