//
//  PokedexInterfaces.swift
//  MyPokedex
//
//  Created by Christian Adiputra on 05/03/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit

protocol PokedexWireframeInterface: WireframeInterface {
    func goToDetail(pokemonId: Int)
    func goToMyPokemon()
}

protocol PokedexViewInterface: ViewInterface {
    func reloadData()
}

protocol PokedexPresenterInterface: PresenterInterface {
    var offSet: Int {
        get
    }
    var pokemons: [PokedexModel]? {
        get
    }
    func getAllPokemon()
    func goToDetail(pokemonId: Int)
    func goToMyPokemon()
}

protocol PokedexInteractorInterface: InteractorInterface {
    func getAllPokemon(offSet: Int)
}

protocol PokedexInteractorOutputInterface: InteractorOutputInterface {
    func didSuccessGetListPokemon(pokemon: [PokedexModel]?)
    func didFailedGetListPokemon(message: String)
}
