//
//  PokedexWireframe.swift
//  MyPokedex
//
//  Created by Christian Adiputra on 05/03/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit

final class PokedexWireframe: BaseWireframe<PokedexViewController> {
    
    // MARK: - Private properties -
    
    // MARK: - Module setup -
    
    init() {
        let moduleViewController = PokedexViewController()
        super.init(viewController: moduleViewController)
        
        let interactor = PokedexInteractor()
        let presenter = PokedexPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }
    
}

// MARK: - Extensions -

extension PokedexWireframe: PokedexWireframeInterface {
    func goToDetail(pokemonId: Int) {
        navigationController?.pushWireframe(DetailPokedexWireframe(pokemonId: pokemonId))
    }
    
    func goToMyPokemon() {
        navigationController?.pushWireframe(MyPokemonListWireframe())
    }
    
}
