//
//  PokedexInteractor.swift
//  MyPokedex
//
//  Created by Christian Adiputra on 05/03/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import NetworkKit

final class PokedexInteractor {
    weak var presenter: PokedexInteractorOutputInterface?
    let pokedexService: PokedexServiceProtocol = PokedexService()
}

// MARK: - Extensions -

extension PokedexInteractor: PokedexInteractorInterface {
    func getAllPokemon(offSet: Int) {
        pokedexService.getAllPokemon(offSet: offSet) { [weak self] response in
            self?.presenter?.didSuccessGetListPokemon(pokemon: response.result)
        } onFailure: { [weak self] error in
            self?.presenter?.didFailedGetListPokemon(message: error.localizedDescription)
        }

    }
    
}
